server:
  port: 0

logging:
  level:
    root: info

spring:
  profiles:
    include:
      - dev
  application:
    name: preOrderProduct-service

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${random.value}
    hostname: localhost